### ISSUE TITLE
When I run python run_inter3d.py --verbal=True --instance_counter_id=1 --number_of_instances=1 --cubeedge=0.05 --pretraining_weights='/media/kontogianni/Samsung_T5/intobjseg/datasets/scannet_official/weights/exp_14_limited_classes/weights_exp14_1 4 .pth' --dataset='scannet' --visual=True --save_results_file=True --results_file_name=results_scannet_mini.txt Such an error occurs, what may be the reason? No error was reported when I installed MinkowskiEngine. My cuda version is 11.1, and MinkowskiEngine is version 0.5.4.

### ISSUE THREAD

**Issue by yueyangwen** [theodorakontogianni/InterObject3D#3]
Traceback (most recent call last):
  File "/home/wyy/git_code/InterObject3D_main/InterObject3D/Minkowski/training/run_inter3d.py", line 221, in <module>
    main(config)
  File "/home/wyy/git_code/InterObject3D_main/InterObject3D/Minkowski/training/run_inter3d.py", line 87, in main
    pred, logits = inseg_model_class.prediction(feats.float(), coords.cpu().numpy(), inseg_global_model, device)
  File "/home/wyy/git_code/InterObject3D_main/InterObject3D/Minkowski/training/interactive_adaptation/interactive_adaptation.py", line 369, in prediction
    sinput = ME.SparseTensor(
  File "/home/wyy/anaconda3/envs/me/lib/python3.9/site-packages/MinkowskiEngine-0.5.4-py3.9-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py", line 275, in __init__
    coordinates, features, coordinate_map_key = self.initialize_coordinates(
  File "/home/wyy/anaconda3/envs/me/lib/python3.9/site-packages/MinkowskiEngine-0.5.4-py3.9-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py", line 338, in initialize_coordinates
    features = spmm_avg.apply(self.inverse_mapping, cols, size, features)
  File "/home/wyy/anaconda3/envs/me/lib/python3.9/site-packages/MinkowskiEngine-0.5.4-py3.9-linux-x86_64.egg/MinkowskiEngine/sparse_matrix_functions.py", line 183, in forward
    result, COO, vals = spmm_average(
  File "/home/wyy/anaconda3/envs/me/lib/python3.9/site-packages/MinkowskiEngine-0.5.4-py3.9-linux-x86_64.egg/MinkowskiEngine/sparse_matrix_functions.py", line 93, in spmm_average
    result, COO, vals = MEB.coo_spmm_average_int32(
RuntimeError: <unknown> at /home/wyy/MinkowskiEngine/src/gpu.cu:100

**Comment by theodorakontogianni** [comment]
Which pytorch version do you use? Python3.9 and Pytorch 1.10.2 should be ok! Do you get any errors when you just import the ME (import MinkowskiEngine as ME)? Another thing to check is what is your "device" and which GPU are you using?

**Comment by yueyangwen** [comment]
Hello,My pytorch version is 1.9.0, python is 3.9, when I just import the ME, there is no problem, my device uses cuda, and my GPU model is NVIDIA GeForce RTX 4090

**Comment by yueyangwen** [comment]
Hello, my problem is solved, I uninstalled all the previously installed environments. Now my cuda version is 11.6, python version 11.9, pytorch version is 1.12.1, MinkowskiEngine is 0.5.4.
